### ISSUE TITLE
Push new QRMs through the framework

### ISSUE THREAD

**Issue by wederbn** [UST-QuAntiL/QuantME-TransformationFramework#4]
__Is your feature request related to a problem? Please describe.__

Currently, the framework is configured with a QRM repository to use for the transformation method.
However, the detector and replacement fragments have to be modeled with the framework, stored, and manually committed to the QRM repository.

__Describe the solution you'd like__

It would be better to incorporate the functionality to push created QRMs to the QRM repository.

**Comment by mbeisel** [comment]
Add _Generate QRM_ button that opens a detector and replacement fragment creation interface, which automatically incorporates task attributes.
Further, an option to directly push the finished QRM can be added.

**Comment by wederbn** [comment]
Follow up at https://github.com/PlanQK/workflow-modeler/issues/4
